export const GET_RANKED_IDEAS_BEGIN = "GET_RANKED_IDEAS_BEGIN";
export const GET_RANKED_IDEAS_SUCCESS = "GET_RANKED_IDEAS_SUCCESS";

export const GET_MY_VOTES_BEGIN = "GET_MY_VOTES_BEGIN";
export const GET_MY_VOTES_SUCCESS = "GET_MY_VOTES_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CHANGE_PAGE = "CHANGE_PAGE";
