export const LOGIN_BUTTON = "LOGIN_BUTTON";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const FLIP_CHECK = "FLIP_CHECK";
export const OPEN_LOGIN = "OPEN_LOGIN";
export const OPEN_SIGNUP = "OPEN_SIGNUP";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_USER_MENU = "TOGGLE_USER_MENU";

export const LOGOUT_USER_BEGIN = "LOGOUT_USER_BEGIN";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CREATE_IDEA_BEGIN = "CREATE_IDEA_BEGIN";
export const CREATE_IDEA_SUCCESS = "CREATE_IDEA_SUCCESS";
export const CREATE_IDEA_ERROR = "CREATE_IDEA_ERROR";

export const GET_IDEAS_BEGIN = "GET_IDEAS_BEGIN";
export const GET_IDEAS_SUCESS = "GET_IDEAS_SUCESS";

export const SET_EDIT_IDEA = "SET_EDIT_IDEA";

export const DELETE_IDEA_BEGIN = "DELETE_IDEA_BEGIN";
export const DELETE_IDEA_SUCCESS = "DELETE_IDEA_SUCCESS";

export const EDIT_IDEA_BEGIN = "EDIT_IDEA_BEGIN";
export const EDIT_IDEA_SUCCESS = "EDIT_IDEA_SUCCESS";
export const EDIT_IDEA_ERROR = "EDIT_IDEA_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const STOP_EDITING = "STOP_EDITING";

export const GET_MY_RANKED_IDEAS_BEGIN = "GET_MY_RANKED_IDEAS_BEGIN";
export const GET_MY_RANKED_IDEAS_SUCESS = "GET_MY_RANKED_IDEAS_SUCCESS";
export const GET_MY_RANKED_IDEAS_ERROR = "GET_MY_RANKED_IDEAS_ERROR";

export const CREATE_RANKED_IDEA_BEGIN = "CREATE_RANKED_IDEA_BEGIN";
export const CREATE_RANKED_IDEA_SUCCESS = "CREATE_RANKED_IDEA_SUCCESS";
export const CREATE_RANKED_IDEA_ERROR = "CREATE_RANKED_IDEA_ERROR";

export const DELETE_RANKED_IDEA_BEGIN = "DELETE_RANKED_IDEA_BEGIN";
export const DELETE_RANKED_IDEA_SUCCESS = "DELETE_RANKED_IDEA_SUCCESS";
export const DELETE_RANKED_IDEA_ERROR = "DELETE_RANKED_IDEA_ERROR";

export const GET_MY_VOTES_BEGIN = "GET_MY_VOTES_BEGIN";
export const GET_MY_VOTES_SUCCESS = "GET_MY_VOTES_SUCCESS";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
